---
abstract: 'libraries for creating and parsing FAIR Data Profiles (see http://datafairport.org for more details)'
author:
  - 'Mark Wilkinson (markw [at] illuiminae [dot] com)'
build_requires:
  File::Slurp: 0
  IO::String: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.036, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FAIR_Data
requires:
  JSON: 0
  LWP::Simple: 0
  Moose: 0
  RDF::NS: 0
  RDF::Query: 0
  RDF::Trine::Model: 0
  RDF::Trine::Parser: 0
  RDF::Trine::Serializer: 0
  URI::Escape: 0
  UUID::Generator::PurePerl: 0
version: 0.17
